---
resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/ankit68543/react-concourse.git

- name: node-image
  type: registry-image
  source:
    repository: node
    tag: 16

jobs:
- name: test
  public: true
  plan:
  - get: node-image
  - get: repo
    trigger: true
  - task: install
    image: node-image
    config:
      inputs:
      - name: repo
      outputs:
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["install"]
        dir: repo
  - task: test
    image: node-image
    config:
      inputs:
      - name: repo
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["run", "test"]
        dir: repo
- name: run
  public: true
  plan:
  - get: node-image
  - get: repo
    trigger: true
  - task: install
    image: node-image
    config:
      inputs:
      - name: repo
      outputs:
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["install"]
        dir: repo
  - task: test
    image: node-image
    config:
      inputs:
      - name: repo
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        path: npm
        args: ["run", "start"]
        dir: repo        